[06-Jul-2021 06:17:11 UTC] Drupal\Core\Database\DatabaseAccessDeniedException: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: NO) in /home2/clientsi/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 181 #0 /home2/clientsi/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home2/clientsi/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home2/clientsi/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home2/clientsi/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(171): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home2/clientsi/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home2/clientsi/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home2/clientsi/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(171): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home2/clientsi/public_html/core/lib/Drupal/Core/DrupalKernel.php(547): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home2/clientsi/public_html/core/lib/Drupal/Core/DrupalKernel.php(892): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home2/clientsi/public_html/core/lib/Drupal/Core/DrupalKernel.php(471): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home2/clientsi/public_html/core/lib/Drupal/Core/DrupalKernel.php(705): Drupal\Core\DrupalKernel->boot()
#12 /home2/clientsi/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[06-Jul-2021 06:31:16 UTC] PDOException: SQLSTATE[HY000] [2005] Unknown MySQL server host 'server5.flexicloud' (-2) in /home2/clientsi/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /home2/clientsi/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(174): PDO->__construct('mysql:host=serv...', 'clientsi_illust...', 'uj4w&f$(*-]n', Array)
#1 /home2/clientsi/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#2 /home2/clientsi/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#3 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#4 /home2/clientsi/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#5 /home2/clientsi/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(171): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#6 /home2/clientsi/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#7 /home2/clientsi/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#8 /home2/clientsi/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(171): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#9 /home2/clientsi/public_html/core/lib/Drupal/Core/DrupalKernel.php(547): Drupal\Component\DependencyInjection\Container->get('cache.container')
#10 /home2/clientsi/public_html/core/lib/Drupal/Core/DrupalKernel.php(892): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#11 /home2/clientsi/public_html/core/lib/Drupal/Core/DrupalKernel.php(471): Drupal\Core\DrupalKernel->initializeContainer()
#12 /home2/clientsi/public_html/core/lib/Drupal/Core/DrupalKernel.php(705): Drupal\Core\DrupalKernel->boot()
#13 /home2/clientsi/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#14 {main}
[06-Jul-2021 06:31:17 UTC] PDOException: SQLSTATE[HY000] [2005] Unknown MySQL server host 'server5.flexicloud' (-2) in /home2/clientsi/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /home2/clientsi/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(174): PDO->__construct('mysql:host=serv...', 'clientsi_illust...', 'uj4w&f$(*-]n', Array)
#1 /home2/clientsi/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#2 /home2/clientsi/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#3 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#4 /home2/clientsi/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#5 /home2/clientsi/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(171): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#6 /home2/clientsi/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#7 /home2/clientsi/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#8 /home2/clientsi/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(171): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#9 /home2/clientsi/public_html/core/lib/Drupal/Core/DrupalKernel.php(547): Drupal\Component\DependencyInjection\Container->get('cache.container')
#10 /home2/clientsi/public_html/core/lib/Drupal/Core/DrupalKernel.php(892): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#11 /home2/clientsi/public_html/core/lib/Drupal/Core/DrupalKernel.php(471): Drupal\Core\DrupalKernel->initializeContainer()
#12 /home2/clientsi/public_html/core/lib/Drupal/Core/DrupalKernel.php(705): Drupal\Core\DrupalKernel->boot()
#13 /home2/clientsi/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#14 {main}
[06-Jul-2021 06:31:19 UTC] PDOException: SQLSTATE[HY000] [2005] Unknown MySQL server host 'server5.flexicloud' (-2) in /home2/clientsi/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /home2/clientsi/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(174): PDO->__construct('mysql:host=serv...', 'clientsi_illust...', 'uj4w&f$(*-]n', Array)
#1 /home2/clientsi/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#2 /home2/clientsi/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#3 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#4 /home2/clientsi/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#5 /home2/clientsi/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(171): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#6 /home2/clientsi/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#7 /home2/clientsi/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#8 /home2/clientsi/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(171): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#9 /home2/clientsi/public_html/core/lib/Drupal/Core/DrupalKernel.php(547): Drupal\Component\DependencyInjection\Container->get('cache.container')
#10 /home2/clientsi/public_html/core/lib/Drupal/Core/DrupalKernel.php(892): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#11 /home2/clientsi/public_html/core/lib/Drupal/Core/DrupalKernel.php(471): Drupal\Core\DrupalKernel->initializeContainer()
#12 /home2/clientsi/public_html/core/lib/Drupal/Core/DrupalKernel.php(705): Drupal\Core\DrupalKernel->boot()
#13 /home2/clientsi/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#14 {main}
[06-Jul-2021 06:33:23 UTC] PDOException: SQLSTATE[HY000] [2013] Lost connection to MySQL server at 'handshake: reading initial communication packet', system error: 11 in /home2/clientsi/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /home2/clientsi/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(174): PDO->__construct('mysql:host=serv...', 'clientsi_illust...', 'uj4w&f$(*-]n', Array)
#1 /home2/clientsi/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#2 /home2/clientsi/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#3 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#4 /home2/clientsi/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#5 /home2/clientsi/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(171): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#6 /home2/clientsi/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#7 /home2/clientsi/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#8 /home2/clientsi/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(171): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#9 /home2/clientsi/public_html/core/lib/Drupal/Core/DrupalKernel.php(547): Drupal\Component\DependencyInjection\Container->get('cache.container')
#10 /home2/clientsi/public_html/core/lib/Drupal/Core/DrupalKernel.php(892): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#11 /home2/clientsi/public_html/core/lib/Drupal/Core/DrupalKernel.php(471): Drupal\Core\DrupalKernel->initializeContainer()
#12 /home2/clientsi/public_html/core/lib/Drupal/Core/DrupalKernel.php(705): Drupal\Core\DrupalKernel->boot()
#13 /home2/clientsi/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#14 {main}
[06-Jul-2021 06:34:29 UTC] PDOException: SQLSTATE[HY000] [2013] Lost connection to MySQL server at 'handshake: reading initial communication packet', system error: 11 in /home2/clientsi/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /home2/clientsi/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(174): PDO->__construct('mysql:host=serv...', 'clientsi_illust...', 'uj4w&f$(*-]n', Array)
#1 /home2/clientsi/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#2 /home2/clientsi/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#3 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#4 /home2/clientsi/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#5 /home2/clientsi/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(171): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#6 /home2/clientsi/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#7 /home2/clientsi/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#8 /home2/clientsi/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(171): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#9 /home2/clientsi/public_html/core/lib/Drupal/Core/DrupalKernel.php(547): Drupal\Component\DependencyInjection\Container->get('cache.container')
#10 /home2/clientsi/public_html/core/lib/Drupal/Core/DrupalKernel.php(892): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#11 /home2/clientsi/public_html/core/lib/Drupal/Core/DrupalKernel.php(471): Drupal\Core\DrupalKernel->initializeContainer()
#12 /home2/clientsi/public_html/core/lib/Drupal/Core/DrupalKernel.php(705): Drupal\Core\DrupalKernel->boot()
#13 /home2/clientsi/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#14 {main}
[06-Jul-2021 06:45:09 UTC] TypeError: Argument 1 passed to Symfony\Component\HttpFoundation\ParameterBag::replace() must be of the type array, null given, called in /home2/clientsi/public_html/core/lib/Drupal/Core/Routing/RouteProvider.php on line 169 in /home2/clientsi/public_html/vendor/symfony/http-foundation/ParameterBag.php on line 54 #0 /home2/clientsi/public_html/core/lib/Drupal/Core/Routing/RouteProvider.php(169): Symfony\Component\HttpFoundation\ParameterBag->replace(NULL)
#1 /home2/clientsi/public_html/core/lib/Drupal/Core/Routing/Router.php(226): Drupal\Core\Routing\RouteProvider->getRouteCollectionForRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home2/clientsi/public_html/core/lib/Drupal/Core/Routing/Router.php(110): Drupal\Core\Routing\Router->getInitialRouteCollection(Object(Symfony\Component\HttpFoundation\Request))
#3 /home2/clientsi/public_html/core/lib/Drupal/Core/Routing/AccessAwareRouter.php(92): Drupal\Core\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#4 /home2/clientsi/public_html/vendor/symfony/http-kernel/EventListener/RouterListener.php(112): Drupal\Core\Routing\AccessAwareRouter->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#5 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\RequestEvent), 'kernel.request', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher))
#6 /home2/clientsi/public_html/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(142): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\RequestEvent), 'kernel.request', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher))
#7 /home2/clientsi/public_html/vendor/symfony/http-kernel/HttpKernel.php(134): Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch(Object(Symfony\Component\HttpKernel\Event\RequestEvent), 'kernel.request')
#8 /home2/clientsi/public_html/vendor/symfony/http-kernel/HttpKernel.php(80): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#9 /home2/clientsi/public_html/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#10 /home2/clientsi/public_html/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#11 /home2/clientsi/public_html/core/modules/page_cache/src/StackMiddleware/PageCache.php(191): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#12 /home2/clientsi/public_html/core/modules/page_cache/src/StackMiddleware/PageCache.php(128): Drupal\page_cache\StackMiddleware\PageCache->fetch(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#13 /home2/clientsi/public_html/core/modules/page_cache/src/StackMiddleware/PageCache.php(82): Drupal\page_cache\StackMiddleware\PageCache->lookup(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#14 /home2/clientsi/public_html/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#15 /home2/clientsi/public_html/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#16 /home2/clientsi/public_html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#17 /home2/clientsi/public_html/core/lib/Drupal/Core/DrupalKernel.php(706): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#18 /home2/clientsi/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#19 {main}
[06-Jul-2021 07:40:30 UTC] TypeError: Argument 1 passed to Symfony\Component\HttpFoundation\ParameterBag::replace() must be of the type array, null given, called in /home2/clientsi/public_html/core/lib/Drupal/Core/Routing/RouteProvider.php on line 169 in /home2/clientsi/public_html/vendor/symfony/http-foundation/ParameterBag.php on line 54 #0 /home2/clientsi/public_html/core/lib/Drupal/Core/Routing/RouteProvider.php(169): Symfony\Component\HttpFoundation\ParameterBag->replace(NULL)
#1 /home2/clientsi/public_html/core/lib/Drupal/Core/Routing/Router.php(226): Drupal\Core\Routing\RouteProvider->getRouteCollectionForRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home2/clientsi/public_html/core/lib/Drupal/Core/Routing/Router.php(110): Drupal\Core\Routing\Router->getInitialRouteCollection(Object(Symfony\Component\HttpFoundation\Request))
#3 /home2/clientsi/public_html/core/lib/Drupal/Core/Routing/AccessAwareRouter.php(92): Drupal\Core\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#4 /home2/clientsi/public_html/vendor/symfony/http-kernel/EventListener/RouterListener.php(112): Drupal\Core\Routing\AccessAwareRouter->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#5 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\RequestEvent), 'kernel.request', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher))
#6 /home2/clientsi/public_html/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(142): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\RequestEvent), 'kernel.request', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher))
#7 /home2/clientsi/public_html/vendor/symfony/http-kernel/HttpKernel.php(134): Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch(Object(Symfony\Component\HttpKernel\Event\RequestEvent), 'kernel.request')
#8 /home2/clientsi/public_html/vendor/symfony/http-kernel/HttpKernel.php(80): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#9 /home2/clientsi/public_html/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#10 /home2/clientsi/public_html/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#11 /home2/clientsi/public_html/core/modules/page_cache/src/StackMiddleware/PageCache.php(191): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#12 /home2/clientsi/public_html/core/modules/page_cache/src/StackMiddleware/PageCache.php(128): Drupal\page_cache\StackMiddleware\PageCache->fetch(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#13 /home2/clientsi/public_html/core/modules/page_cache/src/StackMiddleware/PageCache.php(82): Drupal\page_cache\StackMiddleware\PageCache->lookup(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#14 /home2/clientsi/public_html/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#15 /home2/clientsi/public_html/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#16 /home2/clientsi/public_html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#17 /home2/clientsi/public_html/core/lib/Drupal/Core/DrupalKernel.php(706): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#18 /home2/clientsi/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#19 {main}
[06-Jul-2021 12:20:29 UTC] TypeError: Argument 2 passed to Symfony\Component\Routing\RouteCollection::add() must be an instance of Symfony\Component\Routing\Route, bool given, called in /home2/clientsi/public_html/core/lib/Drupal/Core/Routing/RouteProvider.php on line 380 in /home2/clientsi/public_html/vendor/symfony/routing/RouteCollection.php on line 74 #0 /home2/clientsi/public_html/core/lib/Drupal/Core/Routing/RouteProvider.php(380): Symfony\Component\Routing\RouteCollection->add('entity.node.can...', false)
#1 /home2/clientsi/public_html/core/lib/Drupal/Core/Routing/RouteProvider.php(180): Drupal\Core\Routing\RouteProvider->getRoutesByPath('/node/197')
#2 /home2/clientsi/public_html/core/lib/Drupal/Core/Routing/Router.php(226): Drupal\Core\Routing\RouteProvider->getRouteCollectionForRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 /home2/clientsi/public_html/core/lib/Drupal/Core/Routing/Router.php(110): Drupal\Core\Routing\Router->getInitialRouteCollection(Object(Symfony\Component\HttpFoundation\Request))
#4 /home2/clientsi/public_html/core/lib/Drupal/Core/Routing/AccessAwareRouter.php(92): Drupal\Core\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#5 /home2/clientsi/public_html/vendor/symfony/http-kernel/EventListener/RouterListener.php(112): Drupal\Core\Routing\AccessAwareRouter->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#6 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\RequestEvent), 'kernel.request', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher))
#7 /home2/clientsi/public_html/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(142): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\RequestEvent), 'kernel.request', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher))
#8 /home2/clientsi/public_html/vendor/symfony/http-kernel/HttpKernel.php(134): Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch(Object(Symfony\Component\HttpKernel\Event\RequestEvent), 'kernel.request')
#9 /home2/clientsi/public_html/vendor/symfony/http-kernel/HttpKernel.php(80): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#10 /home2/clientsi/public_html/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#11 /home2/clientsi/public_html/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#12 /home2/clientsi/public_html/core/modules/page_cache/src/StackMiddleware/PageCache.php(191): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#13 /home2/clientsi/public_html/core/modules/page_cache/src/StackMiddleware/PageCache.php(128): Drupal\page_cache\StackMiddleware\PageCache->fetch(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#14 /home2/clientsi/public_html/core/modules/page_cache/src/StackMiddleware/PageCache.php(82): Drupal\page_cache\StackMiddleware\PageCache->lookup(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#15 /home2/clientsi/public_html/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#16 /home2/clientsi/public_html/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#17 /home2/clientsi/public_html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#18 /home2/clientsi/public_html/core/lib/Drupal/Core/DrupalKernel.php(706): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#19 /home2/clientsi/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#20 {main}
[06-Jul-2021 13:41:15 UTC] TypeError: Argument 2 passed to Symfony\Component\Routing\RouteCollection::add() must be an instance of Symfony\Component\Routing\Route, bool given, called in /home2/clientsi/public_html/core/lib/Drupal/Core/Routing/RouteProvider.php on line 380 in /home2/clientsi/public_html/vendor/symfony/routing/RouteCollection.php on line 74 #0 /home2/clientsi/public_html/core/lib/Drupal/Core/Routing/RouteProvider.php(380): Symfony\Component\Routing\RouteCollection->add('entity.node.can...', false)
#1 /home2/clientsi/public_html/core/lib/Drupal/Core/Routing/RouteProvider.php(180): Drupal\Core\Routing\RouteProvider->getRoutesByPath('/node/197')
#2 /home2/clientsi/public_html/core/lib/Drupal/Core/Routing/Router.php(226): Drupal\Core\Routing\RouteProvider->getRouteCollectionForRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 /home2/clientsi/public_html/core/lib/Drupal/Core/Routing/Router.php(110): Drupal\Core\Routing\Router->getInitialRouteCollection(Object(Symfony\Component\HttpFoundation\Request))
#4 /home2/clientsi/public_html/core/lib/Drupal/Core/Routing/AccessAwareRouter.php(92): Drupal\Core\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#5 /home2/clientsi/public_html/vendor/symfony/http-kernel/EventListener/RouterListener.php(112): Drupal\Core\Routing\AccessAwareRouter->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#6 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\RequestEvent), 'kernel.request', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher))
#7 /home2/clientsi/public_html/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(142): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\RequestEvent), 'kernel.request', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher))
#8 /home2/clientsi/public_html/vendor/symfony/http-kernel/HttpKernel.php(134): Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch(Object(Symfony\Component\HttpKernel\Event\RequestEvent), 'kernel.request')
#9 /home2/clientsi/public_html/vendor/symfony/http-kernel/HttpKernel.php(80): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#10 /home2/clientsi/public_html/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#11 /home2/clientsi/public_html/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#12 /home2/clientsi/public_html/core/modules/page_cache/src/StackMiddleware/PageCache.php(191): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#13 /home2/clientsi/public_html/core/modules/page_cache/src/StackMiddleware/PageCache.php(128): Drupal\page_cache\StackMiddleware\PageCache->fetch(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#14 /home2/clientsi/public_html/core/modules/page_cache/src/StackMiddleware/PageCache.php(82): Drupal\page_cache\StackMiddleware\PageCache->lookup(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#15 /home2/clientsi/public_html/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#16 /home2/clientsi/public_html/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#17 /home2/clientsi/public_html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#18 /home2/clientsi/public_html/core/lib/Drupal/Core/DrupalKernel.php(706): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#19 /home2/clientsi/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#20 {main}
[06-Jul-2021 13:41:30 UTC] TypeError: Argument 2 passed to Symfony\Component\Routing\RouteCollection::add() must be an instance of Symfony\Component\Routing\Route, bool given, called in /home2/clientsi/public_html/core/lib/Drupal/Core/Routing/RouteProvider.php on line 380 in /home2/clientsi/public_html/vendor/symfony/routing/RouteCollection.php on line 74 #0 /home2/clientsi/public_html/core/lib/Drupal/Core/Routing/RouteProvider.php(380): Symfony\Component\Routing\RouteCollection->add('entity.node.can...', false)
#1 /home2/clientsi/public_html/core/lib/Drupal/Core/Routing/RouteProvider.php(180): Drupal\Core\Routing\RouteProvider->getRoutesByPath('/node/197')
#2 /home2/clientsi/public_html/core/lib/Drupal/Core/Routing/Router.php(226): Drupal\Core\Routing\RouteProvider->getRouteCollectionForRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 /home2/clientsi/public_html/core/lib/Drupal/Core/Routing/Router.php(110): Drupal\Core\Routing\Router->getInitialRouteCollection(Object(Symfony\Component\HttpFoundation\Request))
#4 /home2/clientsi/public_html/core/lib/Drupal/Core/Routing/AccessAwareRouter.php(92): Drupal\Core\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#5 /home2/clientsi/public_html/vendor/symfony/http-kernel/EventListener/RouterListener.php(112): Drupal\Core\Routing\AccessAwareRouter->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#6 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\RequestEvent), 'kernel.request', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher))
#7 /home2/clientsi/public_html/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(142): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\RequestEvent), 'kernel.request', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher))
#8 /home2/clientsi/public_html/vendor/symfony/http-kernel/HttpKernel.php(134): Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch(Object(Symfony\Component\HttpKernel\Event\RequestEvent), 'kernel.request')
#9 /home2/clientsi/public_html/vendor/symfony/http-kernel/HttpKernel.php(80): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#10 /home2/clientsi/public_html/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#11 /home2/clientsi/public_html/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#12 /home2/clientsi/public_html/core/modules/page_cache/src/StackMiddleware/PageCache.php(191): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#13 /home2/clientsi/public_html/core/modules/page_cache/src/StackMiddleware/PageCache.php(128): Drupal\page_cache\StackMiddleware\PageCache->fetch(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#14 /home2/clientsi/public_html/core/modules/page_cache/src/StackMiddleware/PageCache.php(82): Drupal\page_cache\StackMiddleware\PageCache->lookup(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#15 /home2/clientsi/public_html/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#16 /home2/clientsi/public_html/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#17 /home2/clientsi/public_html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#18 /home2/clientsi/public_html/core/lib/Drupal/Core/DrupalKernel.php(706): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#19 /home2/clientsi/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#20 {main}
[06-Jul-2021 13:44:49 UTC] Error: Class 'PDO' not found in /home2/clientsi/public_html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 160 #0 /home2/clientsi/public_html/core/lib/Drupal/Core/Database/Database.php(380): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /home2/clientsi/public_html/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 [internal function]: Drupal\Core\Database\Database::getConnection('default')
#3 /home2/clientsi/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\Core\\Dat...', Array)
#4 /home2/clientsi/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(171): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'database')
#5 /home2/clientsi/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\Component\DependencyInjection\Container->get('database', 1)
#6 /home2/clientsi/public_html/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#7 /home2/clientsi/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php(171): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#8 /home2/clientsi/public_html/core/lib/Drupal/Core/DrupalKernel.php(547): Drupal\Component\DependencyInjection\Container->get('cache.container')
#9 /home2/clientsi/public_html/core/lib/Drupal/Core/DrupalKernel.php(892): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#10 /home2/clientsi/public_html/core/lib/Drupal/Core/DrupalKernel.php(471): Drupal\Core\DrupalKernel->initializeContainer()
#11 /home2/clientsi/public_html/core/lib/Drupal/Core/DrupalKernel.php(705): Drupal\Core\DrupalKernel->boot()
#12 /home2/clientsi/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
[06-Jul-2021 13:44:49 UTC] PHP Fatal error:  Interface 'JsonSerializable' not found in /home2/clientsi/public_html/core/lib/Drupal/Component/Render/MarkupInterface.php on line 32
[06-Jul-2021 13:49:07 UTC] TypeError: Argument 2 passed to Symfony\Component\Routing\RouteCollection::add() must be an instance of Symfony\Component\Routing\Route, bool given, called in /home2/clientsi/public_html/core/lib/Drupal/Core/Routing/RouteProvider.php on line 380 in /home2/clientsi/public_html/vendor/symfony/routing/RouteCollection.php on line 74 #0 /home2/clientsi/public_html/core/lib/Drupal/Core/Routing/RouteProvider.php(380): Symfony\Component\Routing\RouteCollection->add('entity.node.can...', false)
#1 /home2/clientsi/public_html/core/lib/Drupal/Core/Routing/RouteProvider.php(180): Drupal\Core\Routing\RouteProvider->getRoutesByPath('/node/197')
#2 /home2/clientsi/public_html/core/lib/Drupal/Core/Routing/Router.php(226): Drupal\Core\Routing\RouteProvider->getRouteCollectionForRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 /home2/clientsi/public_html/core/lib/Drupal/Core/Routing/Router.php(110): Drupal\Core\Routing\Router->getInitialRouteCollection(Object(Symfony\Component\HttpFoundation\Request))
#4 /home2/clientsi/public_html/core/lib/Drupal/Core/Routing/AccessAwareRouter.php(92): Drupal\Core\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#5 /home2/clientsi/public_html/vendor/symfony/http-kernel/EventListener/RouterListener.php(112): Drupal\Core\Routing\AccessAwareRouter->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#6 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\RequestEvent), 'kernel.request', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher))
#7 /home2/clientsi/public_html/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(142): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\RequestEvent), 'kernel.request', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher))
#8 /home2/clientsi/public_html/vendor/symfony/http-kernel/HttpKernel.php(134): Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch(Object(Symfony\Component\HttpKernel\Event\RequestEvent), 'kernel.request')
#9 /home2/clientsi/public_html/vendor/symfony/http-kernel/HttpKernel.php(80): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#10 /home2/clientsi/public_html/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#11 /home2/clientsi/public_html/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#12 /home2/clientsi/public_html/core/modules/page_cache/src/StackMiddleware/PageCache.php(191): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#13 /home2/clientsi/public_html/core/modules/page_cache/src/StackMiddleware/PageCache.php(128): Drupal\page_cache\StackMiddleware\PageCache->fetch(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#14 /home2/clientsi/public_html/core/modules/page_cache/src/StackMiddleware/PageCache.php(82): Drupal\page_cache\StackMiddleware\PageCache->lookup(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#15 /home2/clientsi/public_html/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#16 /home2/clientsi/public_html/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#17 /home2/clientsi/public_html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#18 /home2/clientsi/public_html/core/lib/Drupal/Core/DrupalKernel.php(706): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#19 /home2/clientsi/public_html/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#20 {main}
[06-Jul-2021 13:49:56 UTC] PHP Fatal error:  Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.3.0". You are running 7.2.34. in /home2/clientsi/public_html/vendor/composer/platform_check.php on line 24
[06-Jul-2021 15:48:52 UTC] Uncaught PHP Exception Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: "You have requested a non-existent service "content_translation.manager"." at /home2/clientsi/public_html/core/lib/Drupal/Component/DependencyInjection/Container.php line 151
[11-Jul-2021 10:27:54 UTC] PHP Fatal error:  Maximum execution time of -1 seconds exceeded in /home2/clientsi/public_html/core/lib/Drupal/Core/StreamWrapper/LocalStream.php on line 232
[05-Aug-2021 17:58:22 UTC] Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\HttpException: "The specified #ajax callback is empty or not callable." at /home2/clientsi/public_html/core/lib/Drupal/Core/Form/FormAjaxResponseBuilder.php line 67
[12-Aug-2021 12:25:09 UTC] PHP Fatal error:  Maximum execution time of -1 seconds exceeded in /home2/clientsi/public_html/core/lib/Drupal/Core/StreamWrapper/LocalStream.php on line 232
